# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('film_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ref_to_img', models.TextField()),
                ('added_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('aviable', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pessword', models.CharField(max_length=30)),
            ],
        ),
    ]
